import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect } from 'chai';
import { loadStringSync, loadString } from '../../src/cooper.js';
import { canon, normalize } from '../support/canon.js';
import { options } from './options.js';

/**
 * Differential conformance against the Elixir reference implementation.
 *
 * Every `cases/*.casc` is loaded here with `options.js`, rendered with
 * `canon`, and compared to `<case>.expected.json` -- the reference's own
 * result, generated by `scripts/oracle.exs` (`npm run oracle`; never edit
 * those files by hand). Errors compare by stage only, since messages are
 * each implementation's own.
 *
 * The reference is the authority. Only where a result differs because of
 * the host language would a `<case>.node.json` hold this port's expected
 * result instead, explained in `DIVERGENCES.md`; today there are none.
 */

const dir = path.join(path.dirname(fileURLToPath(import.meta.url)), 'cases');
const cases = fs.readdirSync(dir).filter((f) => f.endsWith('.casc')).sort();

/** @param {() => unknown} load */
function outcome(load) {
  try {
    return { ok: canon(load()) };
  } catch (err) {
    return { error: /** @type {any} */ (err).stage ?? 'unknown', message: /** @type {Error} */ (err).message };
  }
}

/** @param {any} doc */
function comparable(doc) {
  return 'ok' in doc ? { ok: normalize(doc.ok) } : { error: doc.error };
}

describe('conformance with the Elixir reference (test/conformance/cases)', () => {
  for (const name of cases) {
    const base = path.join(dir, name.replace(/\.casc$/, ''));
    const override = `${base}.node.json`;
    const expectedFile = fs.existsSync(override) ? override : `${base}.expected.json`;

    it(`${name}${fs.existsSync(override) ? ' (documented divergence)' : ''}`, async () => {
      const source = fs.readFileSync(path.join(dir, name), 'utf8');
      const opts = options(dir, path.join(dir, name));
      const expected = JSON.parse(fs.readFileSync(expectedFile, 'utf8'));
      const sync = outcome(() => loadStringSync(source, opts));
      expect(comparable(sync), JSON.stringify(sync)).to.deep.equal(comparable(expected));

      let asyncResult;
      try {
        asyncResult = { ok: canon(await loadString(source, opts)) };
      } catch (err) {
        asyncResult = { error: /** @type {any} */ (err).stage };
      }
      expect(comparable(asyncResult), 'async API agrees with sync').to.deep.equal(comparable(sync));
    });
  }
});
